title: Ted Naleid's Notes
github_username: tednaleid
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
theme: minima
google_analytics: UA-103670539-1

header_pages:
  - presentations.md
  - contact.md
